export const SHELL_GAME_SECTION = `
<section id="shellgame" class="view shell-game-view" aria-label="Shell Game">
  <style>
    body:has(#shellgame.active) .tabs{display:none!important}
    html body:has(#shellgame.active.has-admin-background){isolation:isolate!important;background:#000!important}
    html body:has(#shellgame.active.has-admin-background)::before{content:''!important;display:block!important;position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;z-index:-1!important;pointer-events:none!important;background-color:#030202!important;background-image:var(--admin-shellgame-background-image)!important;background-size:cover!important;background-position:center top!important;background-repeat:no-repeat!important}
    html body:has(#shellgame.active.has-admin-background)::after,html body:has(#shellgame.active.has-admin-background) .app::before,html body:has(#shellgame.active.has-admin-background) .app::after{display:none!important;content:none!important;background:none!important;background-image:none!important}
    html body:has(#shellgame.active.has-admin-background) .app,html body:has(#shellgame.active.has-admin-background) main.app,html body:has(#shellgame.active.has-admin-background) .content,html body:has(#shellgame.active.has-admin-background) #shellgame.shell-game-view,html body:has(#shellgame.active.has-admin-background) .top,html body:has(#shellgame.active.has-admin-background) header.top{background:transparent!important;background-color:transparent!important;background-image:none!important}
    .shell-game-view{width:100%;height:100%;min-height:0;max-height:100%;padding:0 10px max(22px,env(safe-area-inset-bottom));box-sizing:border-box;overflow:hidden;background-color:#030202;color:#fff;touch-action:none}
    .shell-game-wrap{width:min(100%,520px);margin:0 auto;padding:8px 0 24px;display:grid;gap:12px}
    .shell-game-hero{position:relative;height:430px;border:0;border-radius:0;overflow:visible;background:transparent;box-shadow:none}
    .shell-game-hero:after{content:none;display:none}
    body:has(#shellgame.active) #brandTitle{font-family:Georgia,'Times New Roman',serif!important;font-size:21px!important;line-height:1!important;font-weight:700!important;letter-spacing:-.035em!important;color:#f5dfcb!important;text-shadow:0 3px 16px rgba(0,0,0,.7)!important}
    .shell-game-status{position:absolute;z-index:7;left:15%;right:15%;top:45px;min-height:18px;text-align:center;color:rgba(255,236,224,.72);font-size:11px;font-weight:800;letter-spacing:.01em;text-shadow:0 3px 9px #000}
    .shell-game-status.win{color:#78efae}.shell-game-status.lose{color:#ff91a7}
    .shell-game-arena{position:absolute;z-index:3;left:0;right:0;bottom:64px;height:275px;perspective:900px;transform:translateY(-20px)}
    .shell-cup-button{--slot-x:0px;--cup-lift:0px;position:absolute;left:50%;bottom:14px;width:34%;max-width:152px;height:190px;padding:0;border:0;background:transparent;color:#f8d8bb;transform:translateX(calc(-50% + var(--slot-x))) translateY(var(--cup-lift));transition:transform .30s cubic-bezier(.18,.82,.22,1),filter .26s ease;z-index:4;-webkit-tap-highlight-color:transparent}
    .shell-cup-button[data-slot="0"],.shell-cup-shadow[data-slot="0"]{--slot-x:max(-26vw,-112px)}
    .shell-cup-button[data-slot="1"],.shell-cup-shadow[data-slot="1"]{--slot-x:0px}
    .shell-cup-button[data-slot="2"],.shell-cup-shadow[data-slot="2"]{--slot-x:min(26vw,112px)}
    .shell-cup-shadow{--slot-x:0px;position:absolute;left:50%;bottom:138px;width:27%;max-width:112px;height:15px;border-radius:50%;background:radial-gradient(ellipse at center,rgba(0,0,0,.66) 0%,rgba(0,0,0,.46) 42%,rgba(0,0,0,.18) 64%,rgba(0,0,0,0) 82%);box-shadow:0 7px 15px rgba(0,0,0,.22);filter:blur(2.8px);transform:translateX(calc(-50% + var(--slot-x))) scaleX(1.08);opacity:.78;pointer-events:none;z-index:2}
    .shell-cup-button{cursor:pointer}
    .shell-cup-button.selectable{filter:brightness(1.04)}
    .shell-cup-button:active{transform:translateX(calc(-50% + var(--slot-x))) translateY(-3px) scale(.975);filter:brightness(1.09)}
    .shell-cup-button.lifted{--cup-lift:-66px}
    .shell-cup{position:absolute;left:50%;bottom:120px;width:100%;height:auto;object-fit:contain;transform:translateX(-50%);filter:drop-shadow(0 5px 4px rgba(0,0,0,.34));pointer-events:none}
    .shell-ball{position:absolute;left:50%;bottom:138px;width:30px;height:30px;border-radius:50%;transform:translateX(-50%) scale(0);opacity:0;background:radial-gradient(circle at 34% 28%,#fff7ca 0 10%,#ffc640 28%,#d76d00 72%,#5a1b00 100%);box-shadow:0 8px 16px rgba(0,0,0,.7),0 0 20px rgba(255,165,48,.22);transition:left .28s ease,transform .25s ease,opacity .2s ease;z-index:3}
    .shell-ball.visible{transform:translateX(-50%) scale(1);opacity:1}
    .shell-guess{display:flex;align-items:center;justify-content:center;gap:7px;margin:1px 0 0;color:rgba(255,244,237,.86);font-size:13px;font-weight:740;transform:translateY(-60px)}.shell-guess i{font-style:normal;color:#d9a87a}
    .shell-game-controls{--shell-wine-top:#5b1430;--shell-wine-mid:#3d0d22;--shell-wine-bottom:#260714;--shell-wine-border:rgba(128,45,76,.92);position:relative;overflow:hidden;padding:14px 13px 13px;border:1px solid rgba(164,132,113,.20);border-radius:23px;background:linear-gradient(180deg,rgba(17,15,14,.95) 0%,rgba(8,7,7,.96) 46%,rgba(4,4,4,.97) 100%);box-shadow:inset 0 1px 0 rgba(255,229,211,.055),inset 0 -1px 0 rgba(255,255,255,.018),0 18px 36px rgba(0,0,0,.34);backdrop-filter:blur(7px) saturate(1.04);-webkit-backdrop-filter:blur(7px) saturate(1.04);transform:translateY(-60px)}.shell-game-controls:before,.shell-game-controls:after{content:"";position:absolute;left:8%;right:8%;height:1px;pointer-events:none;z-index:0}.shell-game-controls:before{top:0;background:linear-gradient(90deg,transparent,rgba(244,205,183,.26),transparent)}.shell-game-controls:after{bottom:0;background:linear-gradient(90deg,transparent,rgba(118,84,68,.20),transparent)}.shell-game-controls>*{position:relative;z-index:1}
    .shell-bet-row{height:60px;display:grid;grid-template-columns:58px minmax(0,1fr) 58px;gap:8px;overflow:visible;background:transparent}
    .shell-bet-row button{position:relative;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(183,156,138,.34);border-radius:17px;background:linear-gradient(180deg,rgba(31,28,27,.80),rgba(11,10,10,.92));color:#f7f2ee;box-shadow:inset 0 1px 0 rgba(255,255,255,.045),0 7px 16px rgba(0,0,0,.18);transition:transform .22s cubic-bezier(.18,.82,.22,1),filter .20s ease,box-shadow .20s ease;-webkit-tap-highlight-color:transparent}.shell-bet-row button:not(:disabled):active{transform:translateY(1px) scale(.975);filter:brightness(1.07);box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 4px 10px rgba(0,0,0,.14)}.shell-step-icon{position:relative;z-index:1;width:20px;height:20px;display:block}.shell-step-icon:before,.shell-step-icon:after{content:"";position:absolute;left:50%;top:50%;width:17px;height:3.2px;border-radius:999px;background:#f5f2ef;transform:translate(-50%,-50%);box-shadow:0 1px 1px rgba(0,0,0,.38)}.shell-step-icon.plus:after{transform:translate(-50%,-50%) rotate(90deg)}.shell-step-icon.minus:after{display:none}
    .shell-bet-value{border:1px solid rgba(183,156,138,.37);border-radius:17px;background:linear-gradient(180deg,rgba(10,9,9,.98),rgba(3,3,3,.98));color:#fff;display:flex!important;align-items:center;justify-content:center;gap:10px;font-size:19px!important;font-weight:850!important;letter-spacing:-.015em;user-select:none;-webkit-user-select:none;-webkit-tap-highlight-color:transparent;box-shadow:inset 0 1px 0 rgba(255,255,255,.028),0 7px 16px rgba(0,0,0,.16);transition:transform .24s cubic-bezier(.18,.82,.22,1),filter .20s ease,box-shadow .20s ease}.shell-bet-value:active{transform:translateY(1px) scale(.988);filter:brightness(1.06);box-shadow:inset 0 1px 0 rgba(255,255,255,.022),0 4px 10px rgba(0,0,0,.13)}.shell-bet-value img{width:30px;height:30px;object-fit:contain}.shell-bet-value small{font-size:13px;font-weight:760;color:rgba(255,255,255,.82);letter-spacing:.01em}
    .shell-presets{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:11px}.shell-preset{height:36px;border:1px solid rgba(173,151,137,.30);border-radius:999px;background:linear-gradient(180deg,rgba(20,18,18,.88),rgba(7,7,7,.94));color:rgba(245,240,236,.88);font-size:11.5px;font-weight:700;box-shadow:inset 0 1px 0 rgba(255,255,255,.035);transition:transform .18s cubic-bezier(.18,.82,.22,1),filter .18s ease}.shell-preset:active{transform:scale(.975);filter:brightness(1.06)}
    .shell-play-button{position:relative;overflow:hidden;isolation:isolate;width:100%;height:69px;margin-top:13px;padding:0;border:1px solid var(--shell-wine-border);border-radius:18px;display:grid;place-items:center;align-content:center;gap:4px;background:radial-gradient(120% 95% at 50% 0%,rgba(103,31,58,.28),transparent 57%),linear-gradient(180deg,var(--shell-wine-top) 0%,var(--shell-wine-mid) 54%,var(--shell-wine-bottom) 100%);box-shadow:inset 0 1px 0 rgba(255,215,226,.16),inset 0 -1px 0 rgba(23,0,9,.70),0 13px 26px rgba(0,0,0,.30);color:#fff4f5;text-shadow:0 1px 1px rgba(0,0,0,.36);transition:transform .16s ease,opacity .18s ease,filter .18s ease}.shell-play-button:before{content:"";position:absolute;left:7%;right:7%;top:0;height:1px;background:linear-gradient(90deg,transparent,rgba(255,225,230,.42),transparent);pointer-events:none}.shell-play-main{position:relative;z-index:1;display:flex;align-items:center;gap:10px;font-size:18px;font-weight:820;letter-spacing:-.02em}.shell-play-main i{font-style:normal;font-size:18px;color:#ffe1cb;filter:drop-shadow(0 1px 1px rgba(0,0,0,.38))}.shell-play-button small{position:relative;z-index:1;font-size:8px;font-weight:700;letter-spacing:.24em;color:rgba(255,221,226,.68)}.shell-play-button:disabled{opacity:.54}.shell-play-button:not(:disabled):active{transform:translateY(1px) scale(.985);filter:brightness(.96)}
    .shell-info-row{display:grid;grid-template-columns:1.02fr 1.12fr .96fr;gap:8px;transform:translateY(-60px)}.shell-info-card{min-width:0;height:57px;padding:8px 9px;border:1px solid rgba(226,188,158,.15);border-radius:17px;background:linear-gradient(145deg,rgba(27,23,22,.80),rgba(7,7,7,.84));color:rgba(255,255,255,.78);display:flex;align-items:center;gap:8px}.shell-info-card>i{font-style:normal;font-size:21px;color:#e4b183}.shell-info-card span{min-width:0;font-size:9px;font-weight:720;line-height:1.2}.shell-info-card small{display:block;margin-top:4px;font-size:7px;letter-spacing:.04em;color:rgba(255,255,255,.45);white-space:nowrap}.shell-result-dots{display:flex;gap:5px;margin-top:6px}.shell-result-dots i{width:9px;height:9px;border-radius:50%;background:rgba(255,255,255,.17)}.shell-result-dots i.win{background:#35bd72}.shell-result-dots i.lose{background:#be3447}
    @media(max-width:380px){.shell-game-view{padding-left:7px;padding-right:7px}.shell-game-hero{height:405px}.shell-game-arena{bottom:58px;height:245px}.shell-cup-button{height:166px}.shell-info-card{padding:7px 6px;gap:5px}.shell-info-card>i{font-size:17px}}
    .shell-game-view.shell-compact .shell-game-hero{height:370px}.shell-game-view.shell-compact .shell-game-arena{bottom:48px;height:225px}.shell-game-view.shell-compact .shell-cup-button{height:154px}.shell-game-view.shell-compact .shell-game-wrap{gap:9px}.shell-game-view.shell-compact .shell-game-controls{padding:11px}.shell-game-view.shell-compact .shell-info-row{display:none}
    @media(prefers-reduced-motion:reduce){.shell-cup-button,.shell-ball{transition-duration:.01ms!important}}
  </style>
  <div class="shell-game-wrap">
    <div class="shell-game-hero">
      <div class="shell-game-status" data-shell-status>Press Play Round to begin</div>
      <div class="shell-game-arena" data-shell-arena>
        <span class="shell-cup-shadow" data-slot="0" aria-hidden="true"></span>
        <span class="shell-cup-shadow" data-slot="1" aria-hidden="true"></span>
        <span class="shell-cup-shadow" data-slot="2" aria-hidden="true"></span>
        <div class="shell-ball" data-shell-ball></div>
        <button class="shell-cup-button" type="button" data-shell-cup="0" data-slot="0" aria-label="Cup 1"><img class="shell-cup" src="/assets/shell-game-cup.webp" alt=""/></button>
        <button class="shell-cup-button" type="button" data-shell-cup="1" data-slot="1" aria-label="Cup 2"><img class="shell-cup" src="/assets/shell-game-cup.webp" alt=""/></button>
        <button class="shell-cup-button" type="button" data-shell-cup="2" data-slot="2" aria-label="Cup 3"><img class="shell-cup" src="/assets/shell-game-cup.webp" alt=""/></button>
      </div>
    </div>
    <div class="shell-guess"><i>♠</i><span>Guess where the ball is hidden</span></div>
    <div class="shell-game-controls">
      <div class="shell-bet-row">
        <button type="button" data-shell-minus aria-label="Decrease bet"><span class="shell-step-icon minus" aria-hidden="true"></span></button>
        <div class="shell-bet-value" data-shell-bet role="button" aria-label="Edit GRAM bet"><img src="/app/api/uploaded-image/ton-icon.png" alt="GRAM"/><span>1</span><small>GRAM</small></div>
        <button type="button" data-shell-plus aria-label="Increase bet"><span class="shell-step-icon plus" aria-hidden="true"></span></button>
      </div>
      <div class="shell-presets">
        <button class="shell-preset" type="button" data-shell-preset="0.1">0.1</button>
        <button class="shell-preset" type="button" data-shell-preset="0.5">0.5</button>
        <button class="shell-preset" type="button" data-shell-preset="1">1.0</button>
        <button class="shell-preset" type="button" data-shell-preset="5">5.0</button>
        <button class="shell-preset" type="button" data-shell-preset="10">10.0</button>
      </div>
      <button class="shell-play-button" type="button" data-shell-play><span class="shell-play-main"><i>▶</i><b>Play Round</b></span><small data-shell-potential>POTENTIAL WIN 2.85 GRAM</small></button>
    </div>
    <div class="shell-info-row">
      <div class="shell-info-card"><span>Recent Results<span class="shell-result-dots" data-shell-results><i></i><i></i><i></i><i></i><i></i></span></span></div>
      <div class="shell-info-card"><i>♢</i><span>Provably Fair<small>100% TRANSPARENT</small></span></div>
      <div class="shell-info-card"><i>▤</i><span>Game Rules<small>HOW TO PLAY</small></span></div>
    </div>
  </div>
  <script>(function(){
    var root=document.getElementById('shellgame');if(!root||root.dataset.shellReady)return;root.dataset.shellReady='1';var screenWidth=window.screen&&Number(window.screen.width)||0,screenHeight=window.screen&&Number(window.screen.height)||0;root.classList.toggle('shell-compact',Math.max(screenWidth,screenHeight)>0&&Math.max(screenWidth,screenHeight)<=720);
    var tg=window.Telegram&&window.Telegram.WebApp,NANO=1000000000,cups=Array.prototype.slice.call(root.querySelectorAll('[data-shell-cup]')),presets=Array.prototype.slice.call(root.querySelectorAll('[data-shell-preset]')),ball=root.querySelector('[data-shell-ball]'),status=root.querySelector('[data-shell-status]'),play=root.querySelector('[data-shell-play]'),playLabel=play.querySelector('.shell-play-main b'),potential=root.querySelector('[data-shell-potential]'),betButton=root.querySelector('[data-shell-bet]'),betText=betButton.querySelector('span'),minus=root.querySelector('[data-shell-minus]'),plus=root.querySelector('[data-shell-plus]'),results=root.querySelector('[data-shell-results]');
    var amounts=[.1,.5,1,5,10],bet=1,state='ready',slots=[0,1,2],timers=[],recent=[],resultsLoadVersion=0;
    function wait(ms){return new Promise(function(resolve){var id=setTimeout(resolve,ms);timers.push(id)})}
    function haptic(kind){try{if(!tg||!tg.HapticFeedback)return;if(kind==='success'||kind==='error')tg.HapticFeedback.notificationOccurred(kind);else tg.HapticFeedback.impactOccurred('light')}catch(e){}}
    function money(value){var text=(Math.round((Number(value)||0)*10000)/10000).toFixed(4);while(text.indexOf('.')>=0&&text.endsWith('0'))text=text.slice(0,-1);if(text.endsWith('.'))text=text.slice(0,-1);return text}
    function readBalance(){return window.VexaTonBalance?Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0)):0}
    function syncBalance(value){var n=Number(value);if(window.VexaTonBalance&&Number.isFinite(n)&&n>=0)window.VexaTonBalance.write(Math.floor(n),0)}
    function setStatus(text,kind){status.textContent=text;status.classList.remove('win','lose');if(kind)status.classList.add(kind)}
    function setBet(value){bet=Math.max(.0001,Math.round((Number(value)||1)*10000)/10000);betText.textContent=money(bet);potential.textContent='POTENTIAL WIN '+money(bet*2.85)+' GRAM'}
    function resetCups(){cups.forEach(function(cup,index){cup.dataset.slot=String(index);cup.classList.remove('lifted','selectable')});slots=[0,1,2];ball.classList.remove('visible');ball.style.left='50%';setPickEnabled(false)}
    function ballLeft(slot){var cup=cups.filter(function(item){return Number(item.dataset.slot)===slot})[0],arena=root.querySelector('[data-shell-arena]');if(!cup||!arena)return'50%';var cupRect=cup.getBoundingClientRect(),arenaRect=arena.getBoundingClientRect(),center=cupRect.left+cupRect.width/2-arenaRect.left;return(Math.max(0,Math.min(arenaRect.width,center))/Math.max(1,arenaRect.width)*100)+'%'}
    function swap(a,b){var first=slots.indexOf(a),second=slots.indexOf(b);slots[first]=b;slots[second]=a;cups[a].dataset.slot=String(second);cups[b].dataset.slot=String(first);haptic('impact')}
    async function shuffle(){for(var i=0;i<9;i++){var a=Math.floor(Math.random()*3),b=(a+1+Math.floor(Math.random()*2))%3;swap(a,b);await wait(270+Math.floor(Math.random()*55))}}
    function setPickEnabled(enabled){cups.forEach(function(cup){cup.classList.toggle('selectable',enabled);cup.setAttribute('aria-disabled',enabled?'false':'true')})}
    function setControlsDisabled(disabled){minus.disabled=disabled;plus.disabled=disabled;betButton.setAttribute('aria-disabled',disabled?'true':'false');presets.forEach(function(item){item.disabled=disabled})}
    function requestPlay(choice){var initData=tg?String(tg.initData||''):'';if(!initData)return Promise.reject(new Error('Open the Mini App inside Telegram'));return fetch('/app/api/shellgame/play',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({initData:initData,amountNano:Math.max(1,Math.floor(bet*NANO)),choice:choice})}).then(function(response){return response.json().catch(function(){return null}).then(function(data){if(!response.ok)throw new Error(data&&data.error||'Could not reveal the ball');return data})})}
    function renderResults(){var dots=results?Array.prototype.slice.call(results.querySelectorAll('i')):[];dots.forEach(function(dot,index){dot.className=recent[index]||''})}
    function loadResults(){var initData=tg?String(tg.initData||''):'';if(!initData)return Promise.resolve();var version=++resultsLoadVersion;return fetch('/app/api/shellgame/results',{method:'GET',headers:{'accept':'application/json','x-telegram-init-data':initData},cache:'no-store'}).then(function(response){return response.ok?response.json():null}).then(function(data){if(version!==resultsLoadVersion||!data||!Array.isArray(data.results))return;recent=data.results.filter(function(item){return item==='win'||item==='lose'}).slice(0,5);renderResults()}).catch(function(){})}
    function addResult(won){resultsLoadVersion+=1;recent.unshift(won?'win':'lose');recent=recent.slice(0,5);renderResults()}
    async function start(){if(state!=='ready')return;var stake=Math.max(1,Math.floor(bet*NANO));if(readBalance()<stake){setStatus('Not enough balance','lose');return}state='shuffling';play.disabled=true;setControlsDisabled(true);resetCups();setStatus('Watch the ball');cups[1].classList.add('lifted');ball.style.left=ballLeft(1);ball.classList.add('visible');haptic('impact');await wait(850);cups[1].classList.remove('lifted');ball.classList.remove('visible');await wait(350);setStatus('Keep your eye on it');await shuffle();state='choosing';setPickEnabled(true);setStatus('Choose a cup');playLabel.textContent='Choose One Cup'}
    async function chooseSlot(selectedSlot){if(state!=='choosing')return;state='revealing';setPickEnabled(false);setStatus('Revealing...');try{var data=await requestPlay(selectedSlot),winning=Number(data.winningCup),winner=cups.filter(function(item){return Number(item.dataset.slot)===winning})[0];syncBalance(data.tonBalanceNano);if(winner)winner.classList.add('lifted');ball.style.left=ballLeft(winning);await wait(230);ball.classList.add('visible');addResult(!!data.win);if(data.win){setStatus('You won '+money(Number(data.payoutNano||0)/NANO)+' GRAM','win');haptic('success')}else{setStatus('The ball was under Cup '+String(winning+1),'lose');haptic('error')}await wait(1900)}catch(error){setStatus(error&&error.message||'Game failed','lose');await wait(1300)}finally{resetCups();state='ready';play.disabled=false;setControlsDisabled(false);playLabel.textContent='Play Round'}}
    cups.forEach(function(cup){cup.setAttribute('aria-disabled','true');cup.addEventListener('click',function(){chooseSlot(Number(cup.dataset.slot))})});
    minus.addEventListener('click',function(){if(state!=='ready')return;var index=0;for(var i=0;i<amounts.length;i++)if(amounts[i]<bet)index=i;setBet(amounts[index])});plus.addEventListener('click',function(){if(state!=='ready')return;var next=amounts[amounts.length-1];for(var i=0;i<amounts.length;i++)if(amounts[i]>bet){next=amounts[i];break}setBet(next)});presets.forEach(function(item){item.addEventListener('click',function(){if(state==='ready')setBet(Number(item.dataset.shellPreset))})});betButton.addEventListener('click',function(event){if(state!=='ready')return;event.preventDefault();var current=money(bet);setTimeout(function(){if(state!=='ready'||!root.classList.contains('active'))return;var value=null;try{value=window.prompt('Enter GRAM bet',current)}catch(e){return}if(value!==null){var parsed=Number(String(value).replace(',','.'));if(Number.isFinite(parsed)&&parsed>0)setBet(parsed)}},180)});play.addEventListener('click',start);
    window.addEventListener('vexa:view-changed',function(event){if(!event.detail)return;if(event.detail.id==='shellgame'){loadResults();return}timers.forEach(clearTimeout);timers=[];state='ready';resetCups();play.disabled=false;setControlsDisabled(false);playLabel.textContent='Play Round';setStatus('Press Play Round to begin')});
    setBet(1);resetCups();loadResults();
  })();</script>
</section>`;
