export const ACTIVITY_CORE_SCRIPT = `
(function(){
  var tg=window.Telegram&&window.Telegram.WebApp;
  var user=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};
  var lastPayload='';
  var lastSection='';
  var firstStatePromise=null;
  var resetHandled=false;
  function activeSection(){var active=document.querySelector('.view.active');return active&&active.id?active.id:'home'}
  function userId(){return String(user.id||localStorage.getItem('ownerId')||'').trim()}
  function resetKey(){var id=userId();return id?'vexa:client-reset-version:'+id:''}
  function resetAllKey(){return 'vexa:client-reset-version:all'}
  function applyServerTonBalance(value){var balance=Math.max(0,Math.floor(Number(value)||0));if(!Number.isFinite(balance))return;try{window.dispatchEvent(new CustomEvent('vexa-ton-balance-sync',{detail:{tonBalanceNano:balance}}))}catch(e){}}
  function needsReset(j){var userReset=String(j&&j.resetVersion||'');var allReset=String(j&&j.resetAllVersion||'');var current='',currentAll='';try{current=localStorage.getItem(resetKey())||'';currentAll=localStorage.getItem(resetAllKey())||''}catch(e){}return Boolean((userReset&&userReset!==current)||(allReset&&allReset!==currentAll))}
  function clearUserCache(j){if(resetHandled)return;resetHandled=true;var id=userId();var userReset=String(j&&j.resetVersion||'');var allReset=String(j&&j.resetAllVersion||'');try{var keepOwner=localStorage.getItem('ownerId')||'';Object.keys(localStorage).forEach(function(k){if(k==='ownerId')return;if(/^vexa:/.test(k)||/^vexa/.test(k)||k.indexOf(id)>=0)localStorage.removeItem(k)});if(keepOwner)localStorage.setItem('ownerId',keepOwner);if(userReset)localStorage.setItem(resetKey(),userReset);if(allReset)localStorage.setItem(resetAllKey(),allReset)}catch(e){}try{sessionStorage.clear()}catch(e){}try{if('caches' in window)caches.keys().then(function(keys){keys.forEach(function(k){if(/^vexa/i.test(k))caches.delete(k)})})}catch(e){}try{window.dispatchEvent(new CustomEvent('vexa-user-cache-reset',{detail:{userId:id}}))}catch(e){}setTimeout(function(){try{location.reload()}catch(e){}},80)}
  var isBanned=false;
  var banOverlayTimer=0;
  function ensureBanOverlay(){var el=document.getElementById('vexaBanOverlay');if(el)return el;var st=document.getElementById('vexaBanOverlayStyle');if(!st){st=document.createElement('style');st.id='vexaBanOverlayStyle';st.textContent='#vexaBanOverlay{position:fixed;left:14px;right:14px;top:calc(78px + env(safe-area-inset-top));z-index:2147483000;padding:12px 14px;border:0!important;border-radius:20px;background:rgba(10,10,10,.58)!important;color:#fff;text-align:center;font:800 13px/1.35 system-ui,-apple-system,Segoe UI,sans-serif;letter-spacing:.01em;backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);box-shadow:none;pointer-events:none;transform:translateY(8px);opacity:0;transition:opacity .18s ease,transform .18s ease;display:flex;align-items:center;justify-content:center;gap:8px}#vexaBanOverlay .vexa-ban-icon{width:17px;height:17px;border-radius:999px;background:#ef4444;color:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:12px;font-weight:950;line-height:1;flex:0 0 auto;overflow:hidden;box-shadow:none!important;filter:none!important;transform:none!important}#vexaBanOverlay .vexa-ban-mark{display:block;line-height:1;transform-origin:50% 58%;will-change:transform}#vexaBanOverlay.show{opacity:1;transform:translateY(0)}#vexaBanOverlay.show .vexa-ban-mark{animation:vexaBanMarkShake .82s cubic-bezier(.22,1.1,.36,1) both}@keyframes vexaBanMarkShake{0%{transform:scale(.72) rotate(0deg)}12%{transform:scale(1.22) rotate(-18deg)}24%{transform:scale(1.08) rotate(17deg)}36%{transform:scale(1.15) rotate(-13deg)}48%{transform:scale(1.05) rotate(11deg)}60%{transform:scale(1.1) rotate(-7deg)}74%{transform:scale(1.03) rotate(4deg)}88%{transform:scale(1.01) rotate(-2deg)}100%{transform:scale(1) rotate(0deg)}}.vexa-user-banned [data-banned-muted]{filter:grayscale(.25);opacity:.68}';document.head.appendChild(st)}el=document.createElement('div');el.id='vexaBanOverlay';el.setAttribute('role','alert');el.innerHTML='<span class="vexa-ban-icon" aria-hidden="true"><span class="vexa-ban-mark">!</span></span><span>Your access to all sections is blocked</span>';document.body.appendChild(el);return el}
  function showBanOverlay(){var el=ensureBanOverlay();clearTimeout(banOverlayTimer);el.classList.remove('show');void el.offsetWidth;requestAnimationFrame(function(){el.classList.add('show')});banOverlayTimer=setTimeout(function(){var current=document.getElementById('vexaBanOverlay');if(current)current.classList.remove('show')},5000)}
  function applyBanState(banned){isBanned=!!banned;document.documentElement.classList.toggle('vexa-user-banned',isBanned);document.body.classList.toggle('vexa-user-banned',isBanned);if(!isBanned){var el=document.getElementById('vexaBanOverlay');if(el)el.remove();clearTimeout(banOverlayTimer)}}
  function isAllowedBannedTarget(target){var el=target&&target.closest?target.closest('[data-view],.tabs .tab,[data-tab]'):null;return !!el}
  function bannedControl(target){if(!isBanned||!target||!target.closest)return null;if(isAllowedBannedTarget(target))return null;return target.closest('button,[role="button"],[data-action],a[href],input,select,textarea')}
  function stopIfBanned(ev){var control=bannedControl(ev.target);if(!control)return;showBanOverlay();if(ev.cancelable!==false)ev.preventDefault();ev.stopPropagation();if(ev.stopImmediatePropagation)ev.stopImmediatePropagation()}
  function applyManualRegion(j){var preference=j&&j.regionPreference,code=String(preference&&preference.mode==='manual'&&preference.countryCode||'').trim().toUpperCase();if(!/^[A-Z]{2}$/.test(code)||window.VexaDetectedCountryCode===code)return;try{window.VexaDetectedCountryCode=code;window.dispatchEvent(new CustomEvent('vexa-country-detected',{detail:{countryCode:code,source:'manual'}}))}catch(e){}}
  function sendActivity(force){if(document.hidden)return Promise.resolve(null);var section=activeSection();var body={userId:userId(),username:user.username||null,firstName:user.first_name||null,avatarUrl:user.photo_url||null,section:section,countryCode:String(window.VexaDetectedCountryCode||'')};if(!body.userId)return Promise.resolve(null);var encoded=JSON.stringify(body);var sectionChanged=section!==lastSection;if(!force&&!sectionChanged&&encoded===lastPayload)return Promise.resolve(null);lastPayload=encoded;lastSection=section;var request=fetch('/app/api/activity',{method:'POST',headers:{'content-type':'application/json'},body:encoded,keepalive:true}).then(function(r){return r.json().catch(function(){return null})}).then(function(j){if(j&&j.ok){if(needsReset(j)){clearUserCache(j);return j}applyManualRegion(j);applyBanState(!!j.banned);if(!j.banned){if(j.tonBalanceNano!==undefined)applyServerTonBalance(j.tonBalanceNano);if(j.winChancePercent!==undefined&&window.VexaGameChance&&window.VexaGameChance.set)window.VexaGameChance.set(j.winChancePercent)}try{window.dispatchEvent(new CustomEvent('vexa-initial-user-state',{detail:j}))}catch(e){}}return j}).catch(function(){return null});if(!firstStatePromise){firstStatePromise=request;window.VexaInitialUserState=request}return request;}
  function smartSync(){sendActivity(false)}
  window.addEventListener('vexa-country-detected',function(){sendActivity(true)});
  document.addEventListener('pointerdown',stopIfBanned,true);
  document.addEventListener('touchstart',stopIfBanned,true);
  document.addEventListener('click',function(ev){if(bannedControl(ev.target)){stopIfBanned(ev);return}var b=ev.target&&ev.target.closest&&ev.target.closest('button');if(b&&(b.getAttribute('data-action')||b.getAttribute('data-tab')||b.closest('.tabs')))setTimeout(function(){smartSync();},120);},true);
  sendActivity(true);
})();
`;
