export const PLAY_ZONE_SHOWCASE_OVERRIDES = `
.play-zone-stage{--play-card-gap:6px;gap:10px!important}
.play-zone-plinko-showcase,#playzone .play-zone-nft-strip{display:none!important}
#playzone .game-card-shell{--play-card-image-fit:fill;width:100%!important;max-width:none!important;display:block!important;position:relative!important;margin:0!important;padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important;overflow:visible!important;animation:none!important;transition:transform .18s ease,opacity .18s ease!important;transform-origin:center top!important}
#playzone .game-card-shell[data-play-zone-card-id="shellgame"]{--play-card-image-fit:cover}
#playzone .game-card-live{width:100%!important;height:auto!important;min-height:0!important;max-height:none!important;display:block!important;position:relative!important;margin:0!important;padding:0!important;border:0!important;border-radius:22px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;box-shadow:0 16px 36px rgba(0,0,0,.30)!important;overflow:hidden!important;-webkit-backdrop-filter:blur(3px) saturate(150%)!important;backdrop-filter:blur(3px) saturate(150%)!important}
#playzone .game-card-live:before{content:''!important;display:block!important;position:absolute!important;left:1px!important;right:1px!important;top:1px!important;height:42%!important;border-radius:21px 21px 12px 12px!important;background:linear-gradient(180deg,rgba(255,255,255,.08),rgba(255,255,255,.025) 42%,rgba(255,255,255,0))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14)!important;pointer-events:none!important;z-index:3!important}
#playzone .game-card-live:after{content:''!important;display:block!important;position:absolute!important;inset:0!important;border-radius:inherit!important;background:linear-gradient(135deg,rgba(255,255,255,.055),rgba(255,255,255,0) 36%,rgba(255,255,255,.025) 100%)!important;pointer-events:none!important;z-index:3!important}
#playzone .game-card-live .game-image{display:block!important;position:relative!important;inset:auto!important;width:auto!important;height:auto!important;margin:var(--play-card-gap)!important;aspect-ratio:3/1!important;border:0!important;outline:0!important;border-radius:16px!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;padding:0!important;z-index:1!important}
#playzone .game-card-live .game-image:before,#playzone .game-card-live .game-image:after{content:none!important;display:none!important}
#playzone .game-card-live .game-image img{display:block!important;position:static!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:var(--play-card-image-fit,fill)!important;object-position:center!important;border:0!important;outline:0!important;border-radius:16px!important;background:transparent!important;box-shadow:none!important}
#playzone .game-card-shell>.game-footer-live{position:absolute!important;left:18px!important;right:18px!important;bottom:10px!important;z-index:5!important;display:flex!important;justify-content:center!important;align-items:center!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important;margin:0!important;pointer-events:none!important}
#playzone .game-card-shell>.game-footer-live:before,#playzone .game-card-shell>.game-footer-live:after{content:none!important;display:none!important}
#playzone .game-card-shell>.game-footer-live .game-players{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:3px!important;background:rgba(0,0,0,.16)!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:999px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.10),0 6px 14px rgba(0,0,0,.22)!important;padding:3px 7px!important;margin:0!important;min-height:18px!important;line-height:1!important;-webkit-backdrop-filter:blur(3px)!important;backdrop-filter:blur(3px)!important}
#playzone .game-card-shell>.game-footer-live .game-players i{width:4px!important;height:4px!important;min-width:4px!important;flex:0 0 4px!important;box-shadow:0 0 0 1px rgba(24,185,106,.12),0 0 5px rgba(24,185,106,.18)!important}
#playzone .game-card-shell>.game-footer-live .game-players i:before{inset:-2px!important;opacity:.22!important}
#playzone .game-card-shell>.game-footer-live .game-players b{font-size:8.5px!important;min-width:17px!important;font-weight:850!important;line-height:1!important;color:rgba(255,255,255,.86)!important;text-shadow:0 4px 10px rgba(0,0,0,.48)!important}
#playzone .game-card-shell>.game-footer-live .game-players em{font-size:7px!important;font-weight:760!important;line-height:1!important;color:rgba(255,255,255,.50)!important;margin-left:0!important}
#playzone .game-card-live.is-soft-entering{transform:scale(.985)!important;opacity:.72!important;filter:brightness(1.05) saturate(1.08)!important}
body.soft-game-entering #playzone{opacity:.96!important;transition:opacity .18s ease!important}
@media(max-width:380px){.play-zone-stage{--play-card-gap:6px}#playzone .game-card-live{height:auto!important;min-height:0!important;max-height:none!important;border-radius:20px!important}#playzone .game-card-live:before{border-radius:19px 19px 11px 11px!important}#playzone .game-card-live .game-image{margin:var(--play-card-gap)!important;border-radius:14px!important}#playzone .game-card-live .game-image img{border-radius:14px!important}#playzone .game-card-shell>.game-footer-live{bottom:9px!important}#playzone .game-card-shell>.game-footer-live .game-players{padding:3px 6px!important;gap:3px!important;min-height:17px!important}#playzone .game-card-shell>.game-footer-live .game-players i{width:4px!important;height:4px!important;min-width:4px!important;flex-basis:4px!important}#playzone .game-card-shell>.game-footer-live .game-players b{font-size:8px!important;min-width:16px!important}#playzone .game-card-shell>.game-footer-live .game-players em{font-size:6.6px!important}}
`;