export const MINIAPP_STYLES = `
:root{color-scheme:dark;--text:#fff;--muted:rgba(255,255,255,.58);--line:rgba(255,255,255,.14);--card:rgba(255,255,255,.055);--section-keyboard-inset:0px;--font-main:"SF Pro Display","SF Pro Text","Inter Variable",Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;--font-num:"SF Pro Text","Inter Variable",Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;font-family:var(--font-main);font-feature-settings:"kern" 1,"liga" 1,"calt" 1,"ss01" 1;text-rendering:geometricPrecision;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html,body{margin:0;height:100%;background:#000!important;color:#fff;overflow:hidden;font-family:var(--font-main);font-optical-sizing:auto}
body{height:100dvh}
button,input,select,textarea{font:inherit;font-family:var(--font-main)}
button{border:0}
b,strong,.top-balance-pill b,#crashMultiplier,#minesMultiplier,#plinkoRowsValue,.stat b,.wave-time,.crash-history span,input{font-family:var(--font-num);font-variant-numeric:tabular-nums lining-nums;font-feature-settings:"tnum" 1,"lnum" 1,"kern" 1}
h1,h2,h3,.brand h1,.hero h2{font-family:var(--font-main);font-weight:850;letter-spacing:-.055em}
.app{position:relative;width:min(100%,560px);height:100dvh;margin:auto;padding:max(env(safe-area-inset-top),var(--tg-safe-area-inset-top,0px),var(--tg-content-safe-area-inset-top,0px)) 16px calc(76px + env(safe-area-inset-bottom));background:#000!important;overflow:hidden}
.top{height:72px;display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:16px}
.brand{display:flex;gap:12px;align-items:center;min-width:0}.brand>div{min-width:0}
.logo,.avatar{width:64px;height:64px;border-radius:26px;object-fit:cover;background:transparent!important;border:0!important;box-shadow:none!important;outline:0!important}
.brand h1{font-size:21px;line-height:1.18;margin:-2px 0 -1px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:178px;padding:2px 1px 3px;min-height:29px}
.brand p{font-size:11px;margin:4px 0 0;color:var(--muted);font-weight:520;letter-spacing:-.01em}
.balance-source{position:absolute!important;width:1px!important;height:1px!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;clip-path:inset(50%)!important;white-space:nowrap!important;opacity:0!important;pointer-events:none!important}
.top-balance-pill{height:44px;max-width:156px;flex:0 0 auto;border-radius:999px;border:1px solid rgba(255,255,255,.18);background:linear-gradient(135deg,rgba(255,255,255,.16),rgba(255,255,255,.045));color:#fff;display:flex;align-items:center;gap:8px;padding:0 11px;backdrop-filter:blur(24px) saturate(1.6);-webkit-backdrop-filter:blur(24px) saturate(1.6);box-shadow:0 18px 55px rgba(0,0,0,.42),inset 0 1px 0 rgba(255,255,255,.22)}
.top-balance-pill b{font-size:12.5px;font-weight:760;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;letter-spacing:-.025em}.ton-mini-icon{width:26px;height:26px;display:grid;place-items:center;flex:0 0 auto}.ton-mini-icon svg{width:26px;height:26px;display:block}
.content{height:calc(100dvh - 72px - 94px - env(safe-area-inset-top) - env(safe-area-inset-bottom));overflow:hidden}
.view{display:none;height:100%;overflow:auto;padding-bottom:8px;position:relative}.view.active{display:block}.view.view-transition-in{will-change:opacity,transform;animation:vexa-section-crossfade .42s cubic-bezier(.22,.75,.2,1) both}@keyframes vexa-section-crossfade{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){.view.view-transition-in{animation:none}}
.app:has(#predictzone.active) .content{overflow:visible!important}
.app:has(#predictzone.active) #predictzone.predict-zone-view{overflow:visible!important;overscroll-behavior:none!important;-webkit-overflow-scrolling:auto!important}
.app:has(#predictzone.active) #predictzone .predict-zone-category-menu{margin-left:-16px!important;margin-right:-16px!important;width:calc(100% + 32px)!important;max-width:none!important}
.hero h2{font-size:clamp(46px,13vw,72px);line-height:.88;margin:12px 0 10px}.hero p{color:var(--muted);line-height:1.45;margin:0 0 16px;font-weight:470;letter-spacing:-.015em}
.card,.glass-card{border:1px solid var(--line);border-radius:30px;background:linear-gradient(180deg,rgba(255,255,255,.105),rgba(255,255,255,.03));box-shadow:0 28px 80px rgba(0,0,0,.75),inset 0 1px 0 rgba(255,255,255,.10);margin-bottom:13px;backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px)}
.pad{padding:16px}.title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:13px}.title h3{margin:0;font-size:16px;font-weight:760;letter-spacing:-.035em}.title span,.tiny,label{font-size:12px;color:var(--muted);font-weight:520;letter-spacing:-.01em}label{font-size:10.5px;letter-spacing:.085em;text-transform:uppercase;font-weight:720}
.field{display:grid;gap:8px;margin:12px 0}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:20px;background:#030303;color:#fff;outline:0;padding:0 14px;font-weight:560;letter-spacing:-.015em}input,select{height:52px}textarea{min-height:178px;resize:none;padding:14px;line-height:1.45}
.actions,.stats,.toolbar{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stats{grid-template-columns:repeat(3,1fr)}.toolbar{grid-template-columns:repeat(3,1fr);margin-top:12px}
.primary,.secondary,.ghost,.danger{height:50px;border-radius:20px;display:flex;align-items:center;justify-content:center;font-weight:760;letter-spacing:-.025em}.primary{background:#fff;color:#050505;box-shadow:0 0 24px rgba(255,255,255,.2)}.secondary,.ghost,.danger{border:1px solid var(--line);background:rgba(255,255,255,.075);color:#fff}.ghost,.danger{height:42px;font-size:12px}
.stat,.notice{border:1px solid rgba(255,255,255,.12);border-radius:24px;background:var(--card);padding:13px;color:var(--muted);font-weight:470;letter-spacing:-.01em}.stat b{display:block;color:#fff;font-size:24px;font-weight:760;letter-spacing:-.04em}.stat span{font-size:11px}.list{display:grid;gap:9px;max-height:300px;overflow:auto}
.bot-row{width:100%;display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid rgba(255,255,255,.12);border-radius:25px;background:rgba(255,255,255,.06);color:#fff;padding:10px;text-align:left}.bot-row strong,.bot-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bot-row strong{font-weight:720;letter-spacing:-.025em}.bot-row small,.pill{color:var(--muted);font-weight:500}.pill{border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:11px}.avatar{width:48px;height:48px;border-radius:50%}.avatar-fallback{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;color:#fff;font-weight:800;font-size:17px;background:rgba(255,255,255,.08)}
.tabs{position:absolute;left:0;right:0;bottom:calc(12px + env(safe-area-inset-bottom));width:392px;max-width:calc(100% - 32px);height:58px;margin:0 auto;border:1px solid var(--line);border-radius:25px;background:rgba(5,5,5,.9);display:grid;grid-template-columns:repeat(3,1fr);gap:4px;padding:6px;backdrop-filter:blur(22px);z-index:80;overflow:hidden;transform:translateY(0);transition:opacity .22s ease,transform .28s cubic-bezier(.2,.8,.2,1),width .28s cubic-bezier(.2,.8,.2,1)}.tab{height:100%;min-width:0;border-radius:18px;background:transparent;color:var(--muted);display:grid;place-items:center;font-weight:680;font-size:14px;line-height:1.18;letter-spacing:-.015em;padding:2px 8px 3px;overflow:visible;white-space:nowrap;transition:background .22s ease,color .22s ease,box-shadow .24s ease}.tab:active{transform:scale(.96)}.tab.active{background:#fff;color:#050505;transform:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.45),0 0 18px rgba(255,255,255,.12)}
.toast{position:fixed;left:max(16px,calc((100vw - 528px)/2 + 16px));right:auto;bottom:calc(82px + env(safe-area-inset-bottom));width:max-content;max-width:min(420px,calc(100vw - 32px));min-height:42px;padding:11px 18px;border:1px solid rgba(255,255,255,.18);border-radius:22px;background:linear-gradient(145deg,rgba(255,255,255,.14),rgba(18,18,18,.72));box-shadow:0 18px 58px rgba(0,0,0,.58),inset 0 1px 0 rgba(255,255,255,.16);backdrop-filter:blur(22px) saturate(1.5);-webkit-backdrop-filter:blur(22px) saturate(1.5);display:none;z-index:90;font-size:15px;font-weight:620;line-height:1.25;letter-spacing:-.02em;white-space:normal}
.view.is-section-locked>*:not(.section-locked-view){display:none!important}
.section-locked-view{position:absolute;inset:0;display:grid;place-items:center;z-index:10;background:#000;color:#fff;padding:24px 24px calc(24px + env(safe-area-inset-bottom));text-align:center;pointer-events:auto;transition:padding .28s cubic-bezier(.2,.8,.2,1)}
.section-locked-card{display:grid;justify-items:center;gap:10px;max-width:260px;margin:auto;transition:transform .34s cubic-bezier(.2,.8,.2,1),opacity .24s ease}.section-locked-card svg{width:54px;height:54px;color:#fff;opacity:.9}.section-lock-image{width:min(148px,48vw);height:min(148px,48vw);object-fit:contain;display:block;border:0;background:transparent;box-shadow:none}.section-locked-card h2{margin:4px 0 0;font-size:19px;font-weight:760;letter-spacing:-.04em;line-height:1.1}.section-locked-card p{margin:0;color:rgba(255,255,255,.52);font-size:12px;font-weight:470}.code-card{gap:9px}.section-code-input{width:100%;height:38px;border-radius:999px;border:1px solid rgba(255,255,255,.16);background:#050505;color:#fff;text-align:center;font-size:13px;margin-top:5px;touch-action:manipulation}.section-code-submit{width:100%;height:38px;border-radius:999px;background:#fff;color:#050505;font-weight:760;font-size:13px}.section-code-status{min-height:15px;color:rgba(255,255,255,.58);font-size:11px}
.section-keyboard-dismiss{position:fixed;right:22px;bottom:calc(var(--section-keyboard-inset) + 12px);width:46px;height:46px;border-radius:999px;background:rgba(18,18,18,.94);border:1px solid rgba(255,255,255,.15);color:#fff;display:grid;place-items:center;z-index:120;opacity:0;transform:translateY(14px) scale(.86);pointer-events:none;transition:opacity .22s ease,transform .28s cubic-bezier(.2,.8,.2,1),bottom .28s cubic-bezier(.2,.8,.2,1);box-shadow:0 18px 60px rgba(0,0,0,.55)}
body.section-code-keyboard-open .tabs{opacity:0;transform:translateY(78px);pointer-events:none}
body.section-code-keyboard-open .section-code-view{align-items:end;padding:24px 24px calc(var(--section-keyboard-inset) + 74px)}
body.section-code-keyboard-open .section-code-view .code-card{transform:translateY(0) scale(.98);gap:8px;max-width:300px;width:min(100%,300px)}
body.section-code-keyboard-open .section-code-view .section-lock-image{width:76px;height:76px;transition:width .28s ease,height .28s ease}
body.section-code-keyboard-open .section-code-view h2{font-size:18px}
body.section-code-keyboard-open .section-code-view p{font-size:11px}
body.section-code-keyboard-open .section-code-view .section-code-input{height:42px;font-size:15px;background:#070707}
body.section-code-keyboard-open .section-code-view .section-code-submit{height:42px}
body.section-code-keyboard-open .section-keyboard-dismiss{opacity:1;transform:translateY(0) scale(1);pointer-events:auto}
`;
