export const DICE_SECTION = [
  `<section id="dice" class="view dice-view"><style>body:has(#dice.active) .content`,
  `{margin-left:-16px!important;margin-right:-16px!important;width:calc(100% + 32px)!important}`,
  `body:has(#dice.active) .tabs{display:none!important}.dice-view{position:relative;height:100dvh;min-height:100dvh;`,
  `padding:0 14px calc(96px + env(safe-area-inset-bottom));background:transparent!important;background-image:none!important;`,
  `color:#fff;overflow-y:auto!important;overflow-x:hidden;-webkit-overflow-scrolling:touch;border-radius:0!important;`,
  `box-sizing:border-box!important}.dice-view:before{display:none!important}.dice-wrap{position:relative;z-index:1;`,
  `max-width:520px;min-height:calc(100dvh - 238px);margin:0 auto;display:flex;flex-direction:column;`,
  `justify-content:flex-end;gap:13px;padding:10px 0 0}.dice-status{min-height:25px;text-align:center;font-size:13px;`,
  `font-weight:850;color:rgba(255,255,255,.54);letter-spacing:-.02em}.dice-status.win{color:rgba(255,255,255,.94)}`,
  `.dice-status.lose{color:rgba(255,255,255,.42)}.dice-range-card{position:relative;background:transparent!important;`,
  `border:0!important;box-shadow:none!important;padding:0;display:grid;gap:3px;margin:0 -8px 2px;`,
  `transform:translateY(-10px)}.dice-track-labels{position:relative;z-index:2;height:20px;color:rgba(255,255,255,.42);`,
  `font-size:19px;font-weight:760;line-height:1;letter-spacing:-.035em;padding:0 19px;transform:translateY(12px);`,
  `pointer-events:none}.dice-track-labels span{position:absolute;top:0;text-align:center;transform:translateX(-50%)}`,
  `.dice-track-labels span:nth-child(1){left:19px}.dice-track-labels span:nth-child(2){left:calc(25% + 9.5px)}`,
  `.dice-track-labels span:nth-child(3){left:50%}.dice-track-labels span:nth-child(4){left:calc(75% - 9.5px)}`,
  `.dice-track-labels span:nth-child(5){left:calc(100% - 19px)}.dice-slider-shell{--dice-target-pos:50%;`,
  `--dice-fill-pos:50%;--dice-roll-pos:50%;--dice-left-color:rgba(58,6,20,.84);--dice-right-color:rgba(6,55,24,.84);`,
  `position:relative;height:78px;border-radius:0;background:transparent!important;box-shadow:none!important;`,
  `border:0!important;padding:24px 6px 18px;overflow:visible}.dice-slider-shell:before{content:'';position:absolute;`,
  `left:20px;right:20px;top:6px;height:10px;background:linear-gradient(90deg,rgba(255,255,255,.10) 0 2px,`,
  `transparent 2px 25%,rgba(255,255,255,.10) 25% calc(25% + 2px),transparent calc(25% + 2px) 50%,rgba(255,255,255,.10)`,
  ` 50% calc(50% + 2px),transparent calc(50% + 2px) 75%,rgba(255,255,255,.10) 75% calc(75% + 2px),`,
  `transparent calc(75% + 2px) 100%);clip-path:polygon(0 100%,1.6% 0,3.2% 100%,25% 100%,26.6% 0,28.2% 100%,50% 100%,`,
  `51.6% 0,53.2% 100%,75% 100%,76.6% 0,78.2% 100%,100% 100%);opacity:.56}.dice-slider-visual{position:absolute;`,
  `left:8px;right:8px;top:50%;height:30px;border-radius:999px;transform:translateY(-50%);background:rgba(255,255,255,`,
  `.06);border:1px solid rgba(255,255,255,.15);box-shadow:0 16px 36px rgba(0,0,0,.36),inset 0 1px 0 rgba(255,255,255,`,
  `.20),inset 0 -1px 0 rgba(0,0,0,.55);backdrop-filter:blur(6px) saturate(1.15);-webkit-backdrop-filter:blur(6px)`,
  ` saturate(1.15)}.dice-slider-visual:before{content:'';position:absolute;left:11px;right:11px;top:50%;height:12px;`,
  `border-radius:999px;transform:translateY(-50%);background:linear-gradient(90deg,var(--dice-left-color) 0%,`,
  `var(--dice-left-color) var(--dice-fill-pos),var(--dice-right-color) var(--dice-fill-pos),var(--dice-right-color)`,
  ` 100%);box-shadow:inset 0 1px 0 rgba(255,255,255,.10),0 0 14px rgba(0,0,0,.42)}`,
  `.dice-slider-thumb{position:absolute;left:var(--dice-target-pos);top:50%;width:40px;height:40px;border-radius:13px;`,
  `background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.34);box-shadow:0 14px 34px rgba(0,0,0,.58),`,
  `inset 0 1px 0 rgba(255,255,255,.42),inset 0 -1px 0 rgba(255,255,255,.06);backdrop-filter:blur(8px) saturate(1.4);`,
  `-webkit-backdrop-filter:blur(8px) saturate(1.4);transform:translate(-50%,-50%);`,
  `transition:left .10s cubic-bezier(.2,.8,.2,1),transform .16s ease,box-shadow .16s ease;pointer-events:none}`,
  `.dice-slider-thumb:before{content:'';position:absolute;left:50%;top:50%;width:17px;height:18px;`,
  `transform:translate(-50%,-50%);background:linear-gradient(90deg,rgba(255,255,255,.58) 0 3px,transparent 3px 7px,`,
  `rgba(255,255,255,.58) 7px 10px,transparent 10px 14px,rgba(255,255,255,.58) 14px 17px);border-radius:2px;`,
  `filter:drop-shadow(0 1px 6px rgba(0,0,0,.35))}.dice-roll-marker{position:absolute;left:var(--dice-roll-pos);`,
  `top:12px;width:0;height:0;transform:translate(-50%,-100%) scale(.88);opacity:0;pointer-events:none;z-index:4;`,
  `transition:left .38s cubic-bezier(.2,.8,.2,1),opacity .18s ease,transform .22s ease;`,
  `background:transparent!important;border:0!important;box-shadow:none!important}.dice-roll-marker:before{content:'▼';`,
  `position:absolute;left:50%;top:0;display:block;width:auto;height:auto;background:transparent!important;`,
  `border:0!important;box-shadow:none!important;color:rgba(255,255,255,.94);font-size:22px;line-height:1;`,
  `transform:translateX(-50%);text-shadow:0 3px 5px rgba(0,0,0,.92),0 9px 18px rgba(0,0,0,.78);`,
  `filter:drop-shadow(0 7px 10px rgba(0,0,0,.78));backdrop-filter:none!important;`,
  `-webkit-backdrop-filter:none!important}.dice-roll-marker:after{display:none!important}`,
  `.dice-slider-shell.has-roll .dice-roll-marker{opacity:1;transform:translate(-50%,-100%) scale(1)}`,
  `.dice-slider-shell.is-sliding .dice-slider-thumb{transform:translate(-50%,-50%) scale(1.055);`,
  `box-shadow:0 18px 40px rgba(0,0,0,.66),inset 0 1px 0 rgba(255,255,255,.50)}.dice-slider{position:absolute;inset:0;`,
  `z-index:3;appearance:none;-webkit-appearance:none;width:100%;height:100%;opacity:0;margin:0;cursor:pointer}`,
  `.dice-slider::-webkit-slider-thumb{-webkit-appearance:none;width:48px;height:48px}`,
  `.dice-slider::-moz-range-thumb{width:48px;height:48px;border:0}.dice-panel{position:relative;border-radius:32px;`,
  `background:#050505;border:1px solid rgba(255,255,255,.10);box-shadow:0 24px 74px rgba(0,0,0,.58),`,
  `inset 0 1px 0 rgba(255,255,255,.08);padding:14px;display:grid;gap:12px}.dice-control-grid{display:grid;`,
  `grid-template-columns:repeat(3,1fr);gap:9px}.dice-field{min-height:84px;border-radius:18px;background:#030303;`,
  `border:1px solid rgba(255,255,255,.10);padding:12px 11px;text-align:left;color:#fff;`,
  `box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.dice-field small{display:block;color:rgba(255,255,255,.50);`,
  `font-size:13px;font-weight:850;letter-spacing:-.02em;white-space:nowrap}.dice-field b{display:flex;`,
  `align-items:center;justify-content:space-between;gap:7px;margin-top:14px;font-size:22px;font-weight:760;`,
  `letter-spacing:-.04em;font-variant-numeric:tabular-nums lining-nums;white-space:nowrap}`,
  `.dice-mode-field{cursor:pointer}.dice-mode-field i{font-style:normal;font-size:18px;color:rgba(255,255,255,.72);`,
  `font-weight:800}.dice-bet{display:grid;grid-template-columns:.74fr 1.52fr .74fr;gap:8px}.dice-bet button,`,
  `.dice-roll-button{height:46px;border-radius:18px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,`,
  `255,.075);color:#fff;font-weight:900;letter-spacing:-.025em}.dice-bet button.active{background:rgba(255,255,255,`,
  `.18);border-color:rgba(255,255,255,.24)}.dice-bet-main{font-size:17px!important;background:rgba(255,255,255,.14)`,
  `!important;border-color:rgba(255,255,255,.20)!important}.dice-bet-editor{position:fixed;inset:0;z-index:50;`,
  `display:block;padding:0;background:rgba(0,0,0,.18);opacity:0;pointer-events:none;transition:opacity .18s ease;`,
  `overflow:hidden}.dice-bet-editor.active{opacity:1;pointer-events:auto}.dice-bet-box{position:absolute;left:50%;`,
  `top:var(--dice-editor-top,42vh);width:min(330px,86vw);border-radius:28px;background:rgba(255,255,255,.035)`,
  `!important;border:0!important;box-shadow:0 28px 90px rgba(0,0,0,.55),inset 0 1px 0 rgba(255,255,255,.12);`,
  `padding:18px;transform:translate(-50%,calc(-50% + 18px)) scale(.96);opacity:.8;`,
  `transition:transform .22s cubic-bezier(.2,.8,.2,1),opacity .22s ease;backdrop-filter:blur(6px);`,
  `-webkit-backdrop-filter:blur(6px)}.dice-bet-editor.active .dice-bet-box{transform:translate(-50%,-50%) scale(1);`,
  `opacity:1}.dice-bet-box small{display:block;text-align:center;color:rgba(255,255,255,.62);font-size:12px;`,
  `font-weight:850;letter-spacing:.12em;text-transform:uppercase}.dice-bet-input{width:100%;height:74px;`,
  `margin:12px 0 14px;border-radius:22px;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.035)`,
  `!important;color:#fff;text-align:center;font-size:34px;font-weight:900;letter-spacing:-.04em;outline:none;`,
  `box-shadow:inset 0 1px 0 rgba(255,255,255,.08);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px)}`,
  `.dice-bet-done{width:100%;height:50px;border-radius:999px;border:1px solid rgba(255,255,255,.16);`,
  `background:rgba(255,255,255,.10);color:#fff;font-size:16px;font-weight:900;backdrop-filter:blur(6px);`,
  `-webkit-backdrop-filter:blur(6px)}.dice-roll-button{height:62px;border-radius:999px;background:linear-gradient(180deg,rgba(255,255,255,.22),rgba(255,255,255,.045)),linear-gradient(135deg,#4b0618,#1b0208 55%,#6b0822);color:#fff;`,
  `border-color:rgba(255,255,255,.22);font-size:18px;box-shadow:0 18px 34px rgba(0,0,0,.58),inset 0 1px 0 rgba(255,255,255,.32),inset 0 -1px 0 rgba(0,0,0,.45),0 0 24px rgba(95,8,32,.36);backdrop-filter:blur(12px) saturate(1.35);`,
  `-webkit-backdrop-filter:blur(12px) saturate(1.35);transition:transform .18s ease,`,
  `opacity .18s ease}.dice-roll-button:active{transform:scale(.975)}.dice-roll-button:disabled{opacity:.58;`,
  `transform:scale(.985)}.dice-roll-button.is-rolling{background:linear-gradient(180deg,rgba(255,255,255,.18),rgba(255,255,255,.035)),linear-gradient(135deg,#3a0412,#120106 60%,#4b0618);color:#fff}.dice-stats{display:grid;`,
  `grid-template-columns:repeat(3,1fr);gap:8px}.dice-stat{border-radius:18px;background:#030303;`,
  `border:1px solid rgba(255,255,255,.08);padding:10px;text-align:center}.dice-stat small{display:block;`,
  `color:rgba(255,255,255,.43);font-size:9.5px;font-weight:850;letter-spacing:.10em;text-transform:uppercase}`,
  `.dice-stat b{display:block;margin-top:4px;font-size:14px;font-weight:900;letter-spacing:-.035em}`,
  `.dice-hidden-roll{display:none!important}@media(max-width:420px){.dice-view{padding-bottom:108px}`,
  `.dice-wrap{min-height:calc(100dvh - 232px);gap:12px}.dice-range-card{margin:0 -10px 2px;transform:translateY(-12px)`,
  `}.dice-track-labels{font-size:18px;height:20px;padding:0 15px;transform:translateY(10px)}`,
  `.dice-track-labels span:nth-child(1){left:15px}.dice-track-labels span:nth-child(2){left:calc(25% + 7.5px)}`,
  `.dice-track-labels span:nth-child(3){left:50%}.dice-track-labels span:nth-child(4){left:calc(75% - 7.5px)}`,
  `.dice-track-labels span:nth-child(5){left:calc(100% - 15px)}.dice-slider-shell{height:68px;padding:21px 4px 17px}`,
  `.dice-slider-shell:before{left:16px;right:16px}.dice-slider-visual{left:4px;right:4px;height:28px}`,
  `.dice-slider-thumb{width:36px;height:36px;border-radius:12px}.dice-slider-thumb:before{width:15px;height:16px;`,
  `background:linear-gradient(90deg,rgba(255,255,255,.58) 0 3px,transparent 3px 6px,rgba(255,255,255,.58) 6px 9px,`,
  `transparent 9px 12px,rgba(255,255,255,.58) 12px 15px)}.dice-roll-marker{top:12px;width:0;height:0}`,
  `.dice-roll-marker:before{font-size:20px}.dice-panel{border-radius:30px}.dice-control-grid{gap:7px}`,
  `.dice-field{min-height:80px;padding:11px 9px}.dice-field small{font-size:12px}.dice-field b{font-size:19px}`,
  `.dice-bet{grid-template-columns:.68fr 1.64fr .68fr}}</style><div class="dice-wrap"><div class="dice-range-card">`,
  `<div class="dice-track-labels"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div>`,
  `<div class="dice-slider-shell" data-dice-slider-wrap><div class="dice-roll-marker"></div>`,
  `<div class="dice-slider-visual"></div><div class="dice-slider-thumb"></div>`,
  `<input class="dice-slider" type="range" min="2" max="98" step="0.01" value="50" data-dice-slider/></div></div>`,
  `<div class="dice-status" data-dice-status>Choose target and roll</div><div class="dice-panel">`,
  `<div class="dice-control-grid"><div class="dice-field"><small>Multiplier</small><b><span data-dice-multiplier>`,
  `1.98</span><span>×</span></b></div><button class="dice-field dice-mode-field" type="button" data-dice-mode-toggle>`,
  `<small data-dice-mode-label>Under</small><b><span data-dice-target>50.00</span><i>↻</i></b></button>`,
  `<div class="dice-field"><small>Win Chance</small><b><span data-dice-chance>50.00</span><span>%</span></b></div>`,
  `</div><div class="dice-bet"><button type="button" data-dice-bet-half>1/2</button>`,
  `<button type="button" class="dice-bet-main active" data-dice-bet-input-open>1</button>`,
  `<button type="button" data-dice-bet-double>2x</button></div>`,
  `<button class="dice-roll-button" type="button" data-dice-play>Roll Dice</button><div class="dice-stats">`,
  `<div class="dice-stat"><small>BET</small><b data-dice-current>1</b></div><div class="dice-stat"><small>`,
  `LAST WIN</small><b data-dice-win>0</b></div><div class="dice-stat"><small>BALANCE</small><b data-dice-balance>0</b>`,
  `</div></div></div><div class="dice-hidden-roll" data-dice-roll>50.00</div>`,
  `<div class="dice-hidden-roll" data-dice-profit>0.98</div></div><div class="dice-bet-editor" data-dice-bet-editor>`,
  `<div class="dice-bet-box"><small>Bet amount</small>`,
  `<input class="dice-bet-input" data-dice-bet-input type="number" min="1" inputmode="decimal" value="1"/>`,
  `<button class="dice-bet-done" type="button" data-dice-bet-done>Done</button></div></div><script>(function()`,
  `{var root=document.getElementById('dice');if(!root||root.dataset.readyStakeDice)return;`,
  `root.dataset.readyStakeDice='1';var rollEl=root.querySelector('[data-dice-roll]'),`,
  `statusEl=root.querySelector('[data-dice-status]'),slider=root.querySelector('[data-dice-slider]'),`,
  `sliderWrap=root.querySelector('[data-dice-slider-wrap]'),targetEl=root.querySelector('[data-dice-target]'),`,
  `chanceEl=root.querySelector('[data-dice-chance]'),multEl=root.querySelector('[data-dice-multiplier]'),`,
  `profitEl=root.querySelector('[data-dice-profit]'),currentEl=root.querySelector('[data-dice-current]'),`,
  `winEl=root.querySelector('[data-dice-win]'),balanceEl=root.querySelector('[data-dice-balance]'),`,
  `playBtn=root.querySelector('[data-dice-play]'),modeToggle=root.querySelector('[data-dice-mode-toggle]'),`,
  `modeLabel=root.querySelector('[data-dice-mode-label]'),`,
  `betInputOpen=root.querySelector('[data-dice-bet-input-open]'),betHalfBtn=root.querySelector('[data-dice-bet-half]')`,
  `,betDoubleBtn=root.querySelector('[data-dice-bet-double]'),betEditor=root.querySelector('[data-dice-bet-editor]'),`,
  `betInput=root.querySelector('[data-dice-bet-input]'),betDone=root.querySelector('[data-dice-bet-done]');`,
  `var tg=window.Telegram&&window.Telegram.WebApp;var NANO=1000000000;var mode='under',bet=1,balance=0,rolling=false,`,
  `audio=null,house=1,lastSlideSound=0,lastHapticStep=-1,uploadedDiceAudioUrl='',uploadedDiceAudioLoaded=false,`,
  `uploadedDiceAudio=null,uploadedDiceBuffer=null,uploadedDiceDecoding=false,rollSoundPrimed=false,`,
  `diceSoundVolume=.12;function money(n){var x=Number(n)||0;return x.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)`,
  `0+$/,'$1')}function fmt(n){return (Math.round(Number(n)*100)/100).toFixed(2)}function clamp(n,min,max)`,
  `{return Math.max(min,Math.min(max,Number(n)||0))}function readBalanceNano()`,
  `{return window.VexaTonBalance?Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0)):Math.max(0,`,
  `Math.floor(balance*NANO))}function readBalanceTon(){return readBalanceNano()/NANO}`,
  `function telegramInitData(){return tg?String(tg.initData||''):''}function syncBalance(value){var n=Number(value);`,
  `if(window.VexaTonBalance&&Number.isFinite(n)&&n>=0)window.VexaTonBalance.write(Math.floor(n),0)}`,
  `function requestRoll(stake,t,m){var initData=telegramInitData();if(!initData)return Promise.reject(new Error('Open the Mini App inside Telegram'));`,
  `return fetch('/app/api/dice/roll',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},`,
  `body:JSON.stringify({initData:initData,amountNano:stake,target:t,mode:m})}).then(function(r){return r.json().catch(function(){return null}).then(function(j){`,
  `if(!r.ok)throw new Error(j&&j.error?j.error:'Dice roll failed');return j})})}function betNano()`,
  `{return Math.max(1,Math.floor((Number(bet)||1)*NANO))}function cleanBet(n){var s=String(n==null?'':n).replace(',',`,
  `'.').trim();if(!s)return 1;return Math.max(.0001,Number(s)||1)}function setBet(n){bet=cleanBet(n);if(betInputOpen)`,
  `betInputOpen.textContent=money(bet);if(betInput)betInput.value=String(money(bet));render()}function openBetEditor()`,
  `{if(rolling)return;var sy=window.scrollY||document.documentElement.scrollTop||0;if(betEditor)`,
  `{var h=(window.visualViewport&&window.visualViewport.height)`,
  `||window.innerHeight||document.documentElement.clientHeight||640;betEditor.style.setProperty('--dice-editor-top',`,
  `Math.round(h*.42)+'px');betEditor.dataset.lockScroll=String(sy);betEditor.classList.add('active')}if(betInput)`,
  `{betInput.value=String(money(bet));setTimeout(function(){try{betInput.focus({preventScroll:true});betInput.select()`,
  `;window.scrollTo(0,sy)}catch(e){try{betInput.focus();betInput.select();window.scrollTo(0,sy)}catch(x){}}},60);`,
  `setTimeout(function(){try{window.scrollTo(0,sy)}catch(e){}},220)}haptic('selection')}function closeBetEditor(apply)`,
  `{if(apply&&betInput)setBet(betInput.value);if(betEditor)betEditor.classList.remove('active')}function ac()`,
  `{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()`,
  `;return audio}function haptic(type){try{if(tg&&tg.HapticFeedback){if(type==='impact')`,
  `tg.HapticFeedback.impactOccurred('light');else tg.HapticFeedback.selectionChanged()}}catch(e){}}function zipSound()`,
  `{try{var a=ac(),len=Math.max(1,Math.floor(a.sampleRate*.018)),buf=a.createBuffer(1,len,a.sampleRate),`,
  `data=buf.getChannelData(0);for(var i=0;i<len;i++){data[i]=(Math.random()*2-1)*(1-i/len)}`,
  `var src=a.createBufferSource(),filter=a.createBiquadFilter(),gain=a.createGain(),t=a.currentTime;`,
  `filter.type='bandpass';filter.frequency.value=1200+target()*5;filter.Q.value=3.6;gain.gain.setValueAtTime(.0001,t);`,
  `gain.gain.linearRampToValueAtTime(.018,t+.003);gain.gain.exponentialRampToValueAtTime(.0001,t+.022);src.buffer=buf;`,
  `src.connect(filter);filter.connect(gain);gain.connect(a.destination);src.start(t);src.stop(t+.026)}catch(e){}}`,
  `function tone(f,d,type,v){try{var a=ac(),o=a.createOscillator(),g=a.createGain(),t=a.currentTime;`,
  `o.type=type||'sine';o.frequency.value=f;g.gain.value=0;o.connect(g);g.connect(a.destination);`,
  `g.gain.linearRampToValueAtTime(v||.02,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.start(t);`,
  `o.stop(t+d+.02)}catch(e){}}function decodeUploadedDiceAudio()`,
  `{if(!uploadedDiceAudioUrl||uploadedDiceBuffer||uploadedDiceDecoding)return;uploadedDiceDecoding=true;`,
  `fetch(uploadedDiceAudioUrl,{cache:'force-cache',credentials:'same-origin'}).then(function(r){return r.arrayBuffer()`,
  `}).then(function(buf){return ac().decodeAudioData(buf)}).then(function(decoded){uploadedDiceBuffer=decoded})`,
  `.catch(function(){}).finally(function(){uploadedDiceDecoding=false})}async function loadUploadedDiceAudio()`,
  `{if(uploadedDiceAudioLoaded)return;uploadedDiceAudioLoaded=true;try{var r=await fetch('/app/api/miniapp-audio',`,
  `{cache:'no-store',credentials:'same-origin'});var data=await r.json();`,
  `if(!r.ok||!data||!data.hasAudio||!data.enabled||!data.url)return;uploadedDiceAudioUrl=String(data.url)`,
  `+(String(data.url).indexOf('?')>-1?'&':'?')+'dice='+Date.now();uploadedDiceAudio=new Audio(uploadedDiceAudioUrl);`,
  `uploadedDiceAudio.volume=diceSoundVolume;uploadedDiceAudio.preload='auto';uploadedDiceAudio.load();`,
  `decodeUploadedDiceAudio()}catch(e){}}function warmUploadedDiceAudio(){try{loadUploadedDiceAudio();`,
  `if(uploadedDiceAudio)uploadedDiceAudio.load();decodeUploadedDiceAudio()}catch(e){}}function playDecodedDiceAudio()`,
  `{try{if(!uploadedDiceBuffer)return false;var a=ac(),src=a.createBufferSource(),gain=a.createGain();`,
  `src.buffer=uploadedDiceBuffer;gain.gain.value=diceSoundVolume;src.connect(gain);gain.connect(a.destination);`,
  `src.start(0);return true}catch(e){return false}}function playUploadedDiceAudio(){try{if(playDecodedDiceAudio())`,
  `return true;if(!uploadedDiceAudioUrl)return false;decodeUploadedDiceAudio();if(!uploadedDiceAudio)`,
  `{uploadedDiceAudio=new Audio(uploadedDiceAudioUrl);uploadedDiceAudio.preload='auto';uploadedDiceAudio.load()}`,
  `uploadedDiceAudio.volume=diceSoundVolume;uploadedDiceAudio.pause();try{uploadedDiceAudio.currentTime=0}catch(e){}`,
  `var p=uploadedDiceAudio.play();if(p&&p.catch)p.catch(function(){});return true}catch(e){return false}}`,
  `function primeRollSound(){if(rolling||readBalanceNano()<betNano())return;ac();warmUploadedDiceAudio();`,
  `rollSoundPrimed=playUploadedDiceAudio();if(!rollSoundPrimed){fallbackDiceThrowSound();rollSoundPrimed=true;`,
  `loadUploadedDiceAudio()}}function fallbackDiceThrowSound(){try{var a=ac(),base=a.currentTime,master=a.createGain(),`,
  `comp=a.createDynamicsCompressor();comp.threshold.value=-24;comp.knee.value=18;comp.ratio.value=3;`,
  `comp.attack.value=.003;comp.release.value=.16;master.gain.value=.12;master.connect(comp);`,
  `comp.connect(a.destination);function impact(t,vol,freq){var len=Math.max(1,Math.floor(a.sampleRate*.045)),`,
  `buf=a.createBuffer(1,len,a.sampleRate),data=buf.getChannelData(0);for(var i=0;i<len;i++){var e=Math.pow(1-i/len,`,
  `2.5);data[i]=(Math.random()*2-1)*e}var noise=a.createBufferSource(),bp=a.createBiquadFilter(),ng=a.createGain();`,
  `bp.type='bandpass';bp.frequency.value=freq;bp.Q.value=4.5;ng.gain.setValueAtTime(.0001,t);`,
  `ng.gain.linearRampToValueAtTime(vol,t+.003);ng.gain.exponentialRampToValueAtTime(.0001,t+.075);noise.buffer=buf;`,
  `noise.connect(bp);bp.connect(ng);ng.connect(master);noise.start(t);noise.stop(t+.09);var osc=a.createOscillator(),`,
  `og=a.createGain();osc.type='triangle';osc.frequency.setValueAtTime(freq*.42,t);`,
  `osc.frequency.exponentialRampToValueAtTime(Math.max(55,freq*.22),t+.055);og.gain.setValueAtTime(.0001,t);`,
  `og.gain.linearRampToValueAtTime(vol*.32,t+.002);og.gain.exponentialRampToValueAtTime(.0001,t+.07);osc.connect(og);`,
  `og.connect(master);osc.start(t);osc.stop(t+.08)}function click(t,vol){var o=a.createOscillator(),g=a.createGain(),`,
  `hp=a.createBiquadFilter();o.type='square';o.frequency.value=1500+Math.random()*900;hp.type='highpass';`,
  `hp.frequency.value=900;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(vol,t+.001);`,
  `g.gain.exponentialRampToValueAtTime(.0001,t+.026);o.connect(hp);hp.connect(g);g.connect(master);o.start(t);`,
  `o.stop(t+.03)}var times=[0,.052,.108,.185,.285,.405];for(var n=0;n<times.length;n++)`,
  `{var t=base+times[n]+Math.random()*.018,vol=.038-(n*.004),freq=560-(n*54)+Math.random()*90;impact(t,vol,freq);`,
  `click(t+.008,.010+(Math.random()*.006))}}catch(e){}}function diceThrowSound(){if(rollSoundPrimed)`,
  `{rollSoundPrimed=false;return}if(playUploadedDiceAudio())return;fallbackDiceThrowSound();loadUploadedDiceAudio()}`,
  `function slideFeedback(){var now=performance.now(),step=Math.floor(target()/2);if(step!==lastHapticStep)`,
  `{lastHapticStep=step;haptic('selection')}if(now-lastSlideSound<82)return;lastSlideSound=now;zipSound()}`,
  `function awardXP(amount,source,metadata){if(window.VexaLevel&&typeof window.VexaLevel.add==='function')window.VexaLevel.add(amount,source,metadata||{section:'dice'})}`,
  `function target(){return Math.max(2,Math.min(98,Number(slider.value)||50))}function chance(){var t=target();`,
  `return mode==='under'?t:100-t}function multiplier(){return (100-house)/chance()}function randomRoll()`,
  `{try{var a=new Uint32Array(1);crypto.getRandomValues(a);return (a[0]/4294967295)*100}catch(e){return Math.random()`,
  `*100}}function render(){balance=readBalanceTon();var t=target(),c=chance(),m=multiplier(),profit=bet*m-bet,`,
  `fillPos=clamp(t,5,95),thumbPos=clamp(t,8,92),leftColor=mode==='under'?'rgba(6,55,24,.84)':'rgba(58,6,20,.84)',`,
  `rightColor=mode==='under'?'rgba(58,6,20,.84)':'rgba(6,55,24,.84)';targetEl.textContent=fmt(t);`,
  `chanceEl.textContent=fmt(c);multEl.textContent=fmt(m);profitEl.textContent=money(profit);`,
  `currentEl.textContent=money(bet);balanceEl.textContent=money(balance);if(betInputOpen)`,
  `betInputOpen.textContent=money(bet);if(modeLabel)modeLabel.textContent=mode==='under'?'Under':'Over';if(sliderWrap)`,
  `{sliderWrap.style.setProperty('--dice-target-pos',thumbPos+'%');sliderWrap.style.setProperty('--dice-fill-pos',`,
  `fillPos+'%');sliderWrap.style.setProperty('--dice-left-color',leftColor);`,
  `sliderWrap.style.setProperty('--dice-right-color',rightColor)}}function setRollMarker(value){if(!sliderWrap)return;`,
  `var pos=clamp(value,5,95);sliderWrap.style.setProperty('--dice-roll-pos',pos+'%');`,
  `sliderWrap.classList.add('has-roll')}function setStatus(text,state){statusEl.textContent=text;`,
  `statusEl.classList.remove('win','lose');if(state)statusEl.classList.add(state)}function finishRoll(){rolling=false;playBtn.disabled=false;`,
  `playBtn.classList.remove('is-rolling');playBtn.textContent='Roll Dice'}function roll(){var stake=betNano();`,
  `if(rolling||readBalanceNano()<stake){setStatus('Not enough balance','lose');return}ac();haptic('impact');`,
  `rolling=true;awardXP(2,'game-start',{section:'dice',event:'roll'});if(sliderWrap)sliderWrap.classList.remove('has-roll');`,
  `playBtn.disabled=true;playBtn.classList.add('is-rolling');playBtn.textContent='Rolling';setStatus('Rolling...',null);diceThrowSound();`,
  `var requestedTarget=target(),requestedMode=mode,settlement=requestRoll(stake,requestedTarget,requestedMode),start=performance.now(),dur=360,last=50,lastTick=0;`,
  `function step(now){var p=Math.min(1,(now-start)/dur);if(now-lastTick>55){lastTick=now;last=randomRoll();rollEl.textContent=fmt(last)}`,
  `if(p<1){requestAnimationFrame(step);return}settlement.then(function(data){var r=Number(data&&data.roll),won=!!(data&&data.win),`,
  `m=Number(data&&data.multiplier)||multiplier(),winNano=Math.max(0,Math.floor(Number(data&&data.payoutNano)||0));`,
  `if(!Number.isFinite(r))throw new Error('Invalid Dice result');syncBalance(data&&data.tonBalanceNano);rollEl.textContent=fmt(r);setRollMarker(r);`,
  `winEl.textContent=money(winNano/NANO);render();awardXP(won?(m>=4?30:12):4,won?'game-win':'game-lose',`,
  `{section:'dice',event:'roll-finish',result:won?'win':'no-win',multiplier:m,chance:Number(data&&data.chance)||chance(),roll:r});`,
  `setStatus((won?'Win '+money(winNano/NANO):'No win')+' • Roll '+fmt(r),won?'win':'lose');if(won)haptic('impact')})`,
  `.catch(function(error){setStatus(error&&error.message?error.message:'Dice roll failed','lose')}).finally(finishRoll)}requestAnimationFrame(step)}`, 
  `if(modeToggle)modeToggle.onclick=function(){if(rolling)return;mode=mode==='under'?'over':'under';render();haptic('selection');`,
  `tone(420,.035,'sine',.01)};if(betHalfBtn)betHalfBtn.onclick=function(){if(rolling)return;setBet(Math.max(.0001,`,
  `bet/2));haptic('selection');tone(420,.035,'sine',.01)};if(betDoubleBtn)betDoubleBtn.onclick=function(){if(rolling)`,
  `return;setBet(Math.min(readBalanceTon()||bet*2,bet*2));haptic('selection');tone(420,.035,'sine',.01)};`,
  `if(betInputOpen)betInputOpen.onclick=openBetEditor;if(betDone)betDone.onclick=function(){closeBetEditor(true)};`,
  `if(betInput){betInput.addEventListener('input',function(){var s=String(betInput.value||'').trim();if(!s)return;`,
  `bet=cleanBet(s);render()});betInput.addEventListener('keydown',function(e){if(e.key==='Enter')closeBetEditor(true)}`,
  `)}if(betEditor)betEditor.addEventListener('click',function(e){if(e.target===betEditor)closeBetEditor(true)});`,
  `window.addEventListener('vexa-ton-balance-sync',render);slider.addEventListener('pointerdown',function()`,
  `{if(sliderWrap)sliderWrap.classList.add('is-sliding');ac();lastHapticStep=-1});slider.addEventListener('pointerup',`,
  `function(){if(sliderWrap)sliderWrap.classList.remove('is-sliding')});slider.addEventListener('pointercancel',`,
  `function(){if(sliderWrap)sliderWrap.classList.remove('is-sliding')});slider.addEventListener('input',function()`,
  `{if(!rolling){render();slideFeedback()}});playBtn.addEventListener('pointerdown',primeRollSound,{passive:true});`,
  `playBtn.onclick=roll;render();loadUploadedDiceAudio()})();</script></section>`,
].join('');
