export const PLINKO_CONTROLS_MODERN_STYLES = `
@keyframes plinkoControlsIn{0%{opacity:0;transform:translateY(14px) scale(.985);filter:blur(3px)}100%{opacity:1;transform:translateY(0) scale(1);filter:blur(0)}}
@keyframes plinkoControlItemIn{0%{opacity:0;transform:translateY(9px)}100%{opacity:1;transform:translateY(0)}}
#plinko .plinko-controls{width:min(92vw,360px)!important;display:grid!important;grid-template-columns:minmax(0,1fr) 124px!important;gap:10px!important;margin:16px auto 0!important;align-items:end!important;padding:14px!important;box-sizing:border-box!important;border:1px solid transparent!important;border-radius:0!important;background:transparent!important;background-image:none!important;border-image-source:url('/assets/plinko-glass/control-panel-new.webp?v=1')!important;border-image-slice:110 fill!important;border-image-width:30px!important;border-image-repeat:stretch!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;position:relative!important;z-index:20!important;overflow:visible!important;isolation:isolate!important;will-change:transform,opacity!important;transition:transform .32s cubic-bezier(.2,.9,.18,1)!important}
#plinko.active .plinko-controls{animation:plinkoControlsIn .48s cubic-bezier(.2,.9,.18,1) both!important}
#plinko .plinko-controls::before,#plinko .plinko-controls::after,#plinko .plinko-stage::before,#plinko .plinko-stage::after{display:none!important;content:none!important;background:none!important;background-image:none!important;box-shadow:none!important}
#plinko .plinko-control-grid,#plinko .plinko-field,#plinko .plinko-bet,#plinko .plinko-stats,#plinko .plinko-stat{display:none!important}
#plinko .plinko-console-row{display:grid!important;gap:5px!important;width:100%!important;min-width:0!important;align-items:end!important;will-change:transform,opacity!important}
#plinko.active .plinko-bet-row{animation:plinkoControlItemIn .38s .07s cubic-bezier(.2,.9,.18,1) both!important}
#plinko.active .plinko-rows-row{animation:plinkoControlItemIn .38s .12s cubic-bezier(.2,.9,.18,1) both!important}
#plinko.active .plinko-risk-row{animation:plinkoControlItemIn .38s .17s cubic-bezier(.2,.9,.18,1) both!important}
#plinko.active .plinko-console-actions{animation:plinkoControlItemIn .38s .22s cubic-bezier(.2,.9,.18,1) both!important}
#plinko .plinko-bet-row{grid-column:1!important}
#plinko .plinko-rows-row{grid-column:2!important}
#plinko .plinko-risk-row{grid-column:1/-1!important}
#plinko .plinko-control-label{color:rgba(238,220,222,.76)!important;font-size:10px!important;font-weight:780!important;letter-spacing:.01em!important;text-transform:none!important;white-space:nowrap!important;transition:color .2s ease,opacity .2s ease!important}
#plinko .plinko-bet-asset{height:44px!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;box-sizing:border-box!important;min-width:0!important;overflow:visible!important;transition:transform .22s cubic-bezier(.2,.9,.18,1)!important}
#plinko .plinko-rows-selector{height:44px!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;box-sizing:border-box!important;min-width:0!important;overflow:visible!important;transition:transform .22s cubic-bezier(.2,.9,.18,1)!important}
#plinko .plinko-bet-asset{display:grid!important;grid-template-columns:minmax(0,1fr) 86px!important;align-items:center!important;gap:7px!important;padding:4px!important}
#plinko .plinko-asset-input{min-width:0!important;height:36px!important;border:1px solid transparent!important;border-radius:0!important;background:transparent!important;background-image:none!important;border-image-source:url('/assets/plinko-glass/point-amount-card.webp?v=2')!important;border-image-slice:184 fill!important;border-image-width:14px!important;border-image-repeat:stretch!important;padding:0 8px!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:18px!important;font-weight:950!important;text-align:center!important;box-shadow:none!important;font-variant-numeric:tabular-nums!important;outline:none!important;letter-spacing:0!important;cursor:pointer!important;touch-action:manipulation!important;transition:transform .13s ease,opacity .16s ease!important}
#plinko .plinko-asset-input:active{transform:scale(.98)!important;opacity:.88!important}
#plinko .plinko-bet-quick{height:36px!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:4px!important;overflow:visible!important}
#plinko .plinko-bet-quick .plinko-asset-hit{height:36px!important;min-width:0!important;border:1px solid transparent!important;border-radius:0!important;background:transparent!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:11px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.02em!important;padding:0!important;box-shadow:none!important;text-shadow:none!important;cursor:pointer!important;touch-action:manipulation!important;overflow:visible!important;transition:transform .13s ease,filter .16s ease!important}
#plinko .plinko-bet-quick .plinko-asset-half{border-image-source:url('/assets/plinko-glass/half-button.webp?v=1')!important;border-image-slice:138 fill!important;border-image-width:13px!important;border-image-repeat:stretch!important}
#plinko .plinko-bet-quick .plinko-asset-double{border-image-source:url('/assets/plinko-glass/double-button.webp?v=1')!important;border-image-slice:138 fill!important;border-image-width:13px!important;border-image-repeat:stretch!important}
#plinko .plinko-bet-quick .plinko-asset-hit:active{transform:scale(.95)!important;filter:brightness(1.12)!important}
#plinko .plinko-asset-input::before{display:none!important;content:none!important}
#plinko .plinko-rows-selector{width:100%!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:4px!important;padding:4px 0!important}
#plinko .plinko-rows-selector button{height:36px!important;min-width:0!important;border:1px solid transparent!important;border-radius:0!important;background:transparent!important;background-image:none!important;border-image-source:url('/assets/plinko-glass/half-button.webp?v=1')!important;border-image-slice:138 fill!important;border-image-width:13px!important;border-image-repeat:stretch!important;color:rgba(238,220,222,.78)!important;-webkit-text-fill-color:rgba(238,220,222,.78)!important;font-size:11px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.02em!important;padding:0!important;box-shadow:none!important;text-shadow:none!important;cursor:pointer!important;touch-action:manipulation!important;overflow:visible!important;transition:transform .18s cubic-bezier(.2,.9,.18,1),filter .18s ease,opacity .18s ease!important;opacity:.42!important;filter:brightness(.62) saturate(.72)!important}
#plinko .plinko-rows-selector button.active{border-image-source:url('/assets/plinko-glass/half-button.webp?v=1')!important;border-image-slice:138 fill!important;border-image-width:13px!important;border-image-repeat:stretch!important;color:#fff!important;-webkit-text-fill-color:#fff!important;opacity:1!important;filter:brightness(1.02) saturate(1.04)!important;transform:scale(1.015)!important}
#plinko .plinko-rows-selector button:active{transform:scale(.95)!important;filter:brightness(1.1)!important}
#plinko .plinko-risk-selector{width:100%!important;height:44px!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important;align-items:center!important;gap:4px!important;padding:2px!important;box-sizing:border-box!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;overflow:visible!important}
#plinko .plinko-risk-selector button{height:40px!important;min-width:0!important;border:0!important;border-radius:0!important;background-color:transparent!important;background-position:center!important;background-size:contain!important;background-repeat:no-repeat!important;color:rgba(238,220,222,.78)!important;-webkit-text-fill-color:rgba(238,220,222,.78)!important;font-size:11px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.02em!important;padding:0!important;box-shadow:none!important;text-shadow:none!important;cursor:pointer!important;touch-action:manipulation!important;overflow:visible!important;transition:transform .18s cubic-bezier(.2,.9,.18,1),filter .18s ease,opacity .18s ease!important;opacity:.66!important;filter:brightness(.70) saturate(.84)!important}
#plinko .plinko-risk-selector button[data-plinko-risk-option="easy"]{background-image:url('/assets/plinko-glass/risk-easy.webp?v=1')!important}
#plinko .plinko-risk-selector button[data-plinko-risk-option="medium"]{background-image:url('/assets/plinko-glass/risk-medium.webp?v=1')!important}
#plinko .plinko-risk-selector button[data-plinko-risk-option="hard"]{background-image:url('/assets/plinko-glass/risk-hard.webp?v=1')!important}
#plinko .plinko-risk-selector button.active{color:#fff!important;-webkit-text-fill-color:#fff!important;opacity:1!important;filter:brightness(1.02) saturate(1.02)!important;transform:scale(1.012)!important}
#plinko .plinko-risk-selector button:active{transform:scale(.96)!important;filter:brightness(1.1)!important}
#plinko .plinko-console-actions{grid-column:1/-1!important;width:100%!important;display:grid!important;grid-template-columns:1fr!important;gap:8px!important;margin:2px 0 0!important;position:relative!important;z-index:20!important;will-change:transform,opacity!important}
#plinko .plinko-drop-asset{width:100%!important;height:42px!important;border:1px solid transparent!important;border-radius:0!important;margin:0!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:13px!important;font-weight:950!important;letter-spacing:-.02em!important;background:transparent!important;background-image:none!important;border-image-source:url('/assets/plinko-glass/control-primary.webp?v=1')!important;border-image-slice:86 fill!important;border-image-width:17px!important;border-image-repeat:stretch!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;cursor:pointer!important;touch-action:manipulation!important;text-shadow:none!important;transition:transform .16s cubic-bezier(.2,.9,.18,1),filter .18s ease!important;position:relative!important;overflow:visible!important;isolation:isolate!important}
#plinko .plinko-drop-asset::before,#plinko .plinko-drop-asset::after{display:none!important;content:none!important;background:none!important;box-shadow:none!important}
#plinko .plinko-drop-asset:active,#plinko .plinko-drop-asset.plinko-drop-tap,#plinko .plinko-drop-asset.plinko-drop-press{transform:scale(.975)!important;filter:brightness(1.12) saturate(1.04)!important}
#plinko .plinko-drop-asset span{display:block!important;color:inherit!important;-webkit-text-fill-color:inherit!important;white-space:nowrap!important;position:relative!important;z-index:1!important}
#plinko .plinko-bet-value,#plinko .plinko-hidden-status{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;left:-9999px!important}
#plinko .plinko-stage{overflow:visible!important;background:transparent!important;background-image:none!important;box-shadow:none!important;border:0!important;filter:none!important}
#plinko .plinko-canvas{clip-path:none!important;background:transparent!important;background-image:none!important}
@media(prefers-reduced-motion:reduce){#plinko.active .plinko-controls,#plinko.active .plinko-console-row,#plinko.active .plinko-console-actions{animation:none!important}#plinko .plinko-controls,#plinko .plinko-bet-asset,#plinko .plinko-rows-selector,#plinko .plinko-risk-selector,#plinko button{transition:none!important}}
@media(max-width:380px){#plinko .plinko-controls{width:min(94vw,360px)!important;grid-template-columns:1fr!important;gap:8px!important;margin-top:14px!important;padding:12px!important}#plinko .plinko-bet-row,#plinko .plinko-rows-row,#plinko .plinko-risk-row{grid-column:1!important}#plinko .plinko-bet-asset,#plinko .plinko-rows-selector,#plinko .plinko-risk-selector{height:42px!important}#plinko .plinko-asset-input{height:34px!important}#plinko .plinko-bet-quick,#plinko .plinko-bet-quick .plinko-asset-hit,#plinko .plinko-rows-selector button{height:34px!important}#plinko .plinko-risk-selector button{height:38px!important}#plinko .plinko-console-actions{grid-column:1!important;width:100%!important}#plinko .plinko-drop-asset{height:42px!important}}
`;
