export const PLINKO_STYLES = `
body:has(#plinko.active) .tabs{display:none!important}
html body:has(#plinko.active){isolation:isolate!important;background:#000!important}
html body:has(#plinko.active)::before{content:""!important;display:block!important;position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;z-index:-1!important;pointer-events:none!important;background-color:#000!important;background-image:url('/assets/Plinko.PNG?v=1')!important;background-size:cover!important;background-position:center top!important;background-repeat:no-repeat!important;transform:none!important;animation:none!important;filter:none!important;opacity:1!important}
html body:has(#plinko.active)::after,html body:has(#plinko.active) .app::before,html body:has(#plinko.active) .app::after{display:none!important;content:none!important;background:none!important;background-image:none!important}
html body:has(#plinko.active) .app,html body:has(#plinko.active) main.app,html body:has(#plinko.active) .content,html body:has(#plinko.active) #plinko.view,html body:has(#plinko.active) .top,html body:has(#plinko.active) header.top{background:transparent!important;background-color:transparent!important;background-image:none!important}
#plinko.view{overflow:hidden}
.plinko-page{height:100%;box-sizing:border-box;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;gap:0;padding:16px 0 132px;position:relative}
.plinko-top{width:auto;display:flex;justify-content:flex-end;position:fixed;top:calc(26px + env(safe-area-inset-top));right:16px;z-index:12;pointer-events:none}
.plinko-credit{height:34px;border-radius:999px;border:0;background:rgba(255,255,255,.035);display:flex;align-items:center;gap:8px;padding:0 12px;color:#fff;font-size:13px;font-weight:900;font-variant-numeric:tabular-nums;overflow:hidden;pointer-events:auto;box-shadow:none;backdrop-filter:blur(3px) saturate(1.12);-webkit-backdrop-filter:blur(3px) saturate(1.12)}
.plinko-credit img{width:22px;height:22px;object-fit:contain;border:0;box-shadow:none;background:transparent;flex:0 0 auto}
.plinko-stage{width:min(105%,402px);aspect-ratio:376/326;display:grid;place-items:center;margin-top:8px;position:relative;z-index:1;flex:0 0 auto;overflow:hidden;padding:10px 2px 0;border:0;border-radius:0;background:transparent;box-shadow:none;backdrop-filter:none;transform:scale(1.025);transform-origin:top center}
.plinko-canvas{width:100%;height:100%;display:block;background:transparent}
.plinko-controls{width:min(100%,374px);display:grid;gap:7px;margin-top:-4px;position:relative;z-index:2;flex:0 0 auto;padding:10px 10px 11px;border:0;border-radius:24px;background:rgba(255,255,255,.025);box-shadow:none;backdrop-filter:blur(3px) saturate(1.12);-webkit-backdrop-filter:blur(3px) saturate(1.12)}
.toast{left:50%!important;right:auto!important;bottom:calc(104px + env(safe-area-inset-bottom))!important;transform:translate3d(-50%,18px,0) scale(.96)!important;max-width:min(86vw,360px)!important;width:max-content!important;min-height:44px!important;padding:0 20px!important;border-radius:22px!important;border:0!important;background:rgba(255,255,255,.055)!important;color:#fff!important;font-size:15px!important;font-weight:850!important;line-height:1.2!important;letter-spacing:-.025em!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;box-shadow:0 18px 42px rgba(0,0,0,.24),inset 0 1px 0 rgba(255,255,255,.15)!important;backdrop-filter:blur(4px) saturate(1.15)!important;-webkit-backdrop-filter:blur(4px) saturate(1.15)!important;opacity:0!important;pointer-events:none!important;transition:opacity .24s ease,transform .28s cubic-bezier(.18,.88,.22,1.08)!important;z-index:140!important}.toast[style*="block"],.toast[style*="flex"]{opacity:1!important;transform:translate3d(-50%,0,0) scale(1)!important}
`;
